name: 01 - Building Blocks

on: workflow_dispatch

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
          - name: Say hello
            run: echo "Heloo World!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
          - name: Succssful step
            run: |
              echo "I'll succeed"
              exit 0
          - name: Say goodbye
            run: echo "Goodbye!"
