
name: 02 - Workflow Events

<<<<<<< HEAD
on: workflow_dispatch
=======
on: 
  pull_request:
  workflow_dispatch:
>>>>>>> 90373c4 (feat(03-workflow-runners): First comment)

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
        - name: show the trigger
          run: echo "I've been triggered by a(n) ${{github.event_name}} event." 
